//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miPrimerProyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedor()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El campo Nombre NO puede ir vacio")]
        [StringLength(20, ErrorMessage = "supero el limite de 20 caracteres del campo Nombre")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El campo Direccion NO puede ir vacio")]
        public string direccion { get; set; }
        [Required(ErrorMessage = "El campo Telefono NO puede ir vacio")]
        public string telefono { get; set; }
        [Required(ErrorMessage = "El campo Nombre de contacto NO puede ir vacio")]
        [StringLength(20, ErrorMessage = "supero el limite de 20 caracteres del campo Nombre")]
        public string nombre_contacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}
